name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  pull_project:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Pull project
        shell: pwsh
        run: |
          cd "C:\Users\Adi Kar\Desktop\learn_github_actions\pp_01_lgha"
          git pull origin main
          # Add any additional steps you need here
