name: Deploy to Windows Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout node
        uses: actions/checkout@v3
      - name: Set up PowerShell Core
        uses: actions/setup-pwsh@v1  # This action sets up PowerShell Core
        with:
          pwsh-version: '7.x'  # You can specify the version you want to use
  pull_project:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: pull project
        shell: pwsh
        run: |
          cd "C:\Users\Adi Kar\Desktop\learn_github_actions\pp_01_lgha"
          git pull origin main
          #test
