name: Deploy to Windows Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout node
        uses: actions/checkout@v3
      - name: Deploy to Windows
        run: |
          $server = "Akar2-PyDev01"
          $username = "adikar"
          $password = "Somu1022"
          $localPath = "./path/files"
          $remotePath = "c:\path"
          $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
          $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $securePassword

          Copy-Item -Path $localPath -Destination "\\$server\$remotePath" -Recurse -Credential $credential
        shell: powershell
