name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  install_powershell_core:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Install PowerShell Core
        run: |
          # Install PowerShell Core
          choco install powershell-core -y
          # Verify the installation
          pwsh -v

  pull_project:
    needs: install_powershell_core  # Make sure it depends on the install step
    runs-on: self-hosted
    steps:
      - name: Pull project
        shell: pwsh
        run: |
          cd "C:\Users\Adi Kar\Desktop\learn_github_actions\pp_01_lgha"
          git pull origin main
          # Add any additional steps you need here
