name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  pull_project:
    needs: deploy  # Make sure it depends on the install step
    runs-on: self-hosted
    steps:
      - name: Pull project
        shell: cmd
        run: |
          icacls "C:\Users\Adi Kar\Desktop\learn_github_actions\pp_01_lgha" /grant:r "NT AUTHORITY\SYSTEM:(OI)(CI)F"
          git pull origin main
