name: Deploy to Windows Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout node
        uses: actions/checkout@v3
  pull_project:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: pull project
        run: |
          Set-ExecutionPolicy Unrestricted
          cd C:\Users\Adi Kar\Desktop\learn_github_actions\pp_01_lgha;; git pull origin main
      
