name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  pull_project:
    needs: deploy  # Make sure it depends on the install step
    runs-on: self-hosted
    steps:
      - name: Pull project
        shell: cmd
        run: |
          cd /d "C:\inetpub\wwwroot\iheart\pp_01_lgha"
          git config --global --add safe.directory C:\inetpub\wwwroot\iheart\pp_01_lgha
          git pull origin main
