name: Lint, Test, Deploy
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Project
        runs: eslint --ext .jsx --fix src
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Test Project
        runs: vitest run
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        runs: vite build
      - name: Deploy Project
        runs: echo "Deploying..."
